#!/usr/bin/with-contenv bash
set -e

export DIMENSION_TITLE=${DIMENSION_TITLE:-Default Title}
export DIMENSION_QUOTE=${DIMENSION_QUOTE:-Mess with the best, Die like the rest}
export DIMENSION_ATTRIBUTION=${DIMENSION_ATTRIBUTION:-Dade Murphy}

confd -onetime -backend env
lighttpd -tt -f /etc/lighttpd/lighttpd.conf
cat /var/www/html/index.html
